# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RoomPlanDemoProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod  'Masonry', :git => 'https://github.com/SnapKit/Masonry.git', :tag => 'v1.1.0'
  # Pods for RoomPlanDemoProj

end
