# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RoomPlanDemoProj' do
  # Pods for RoomPlanDemoProj
  use_frameworks!
  pod 'PinLayout', :git => 'https://github.com/layoutBox/PinLayout.git', :tag => '1.10.3'
end
